"""Declarative per-table column spec for the G1 data console (DG4).

One spec per **input** table. Both the editor screen and the validator read
this -- a rule enforced here cannot be forgotten on one screen and missed on
another. Derived tables (sku_policy, parked_items, sweep_runs,
purchase_requests, audit_events, agent_memory_signals) deliberately have no
entry here at all (DG3): editing them would put a number into the evidence
chain that no computation produced.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date


@dataclass(frozen=True)
class ColumnSpec:
    name: str
    type: type  # str | int | float | bool | date
    label: str = ""
    required: bool = False
    min_value: float | None = None
    max_value: float | None = None
    enum: tuple[str, ...] | None = None
    fk: tuple[str, str] | None = None  # (table, column)
    auto: bool = False  # generated by dataops, not entered by the operator
    not_future: bool = False

    def display_label(self) -> str:
        return self.label or self.name.replace("_", " ").capitalize()


@dataclass(frozen=True)
class TableSpec:
    label: str
    primary_key: str
    columns: list[ColumnSpec]
    unique: tuple[str, ...] | None = None  # R7-style duplicate guard
    dependents: tuple[tuple[str, str], ...] = ()  # (table, fk_column) referencing this table's PK -- delete guard


DERIVED_TABLES = (
    "sku_policy", "parked_items", "sweep_runs", "purchase_requests",
    "audit_events", "agent_memory_signals",
)

# Supplier master/performance and supplier quotes arrive from the purchasing
# data source.  A planner may view them, but must not manufacture a compliant
# supplier, reliability score, or quote from the operator console.
SYSTEM_MANAGED_TABLES = ("vendors", "vendor_offers")

TABLE_SPECS: dict[str, TableSpec] = {
    "products": TableSpec(
        label="Products",
        primary_key="sku",
        columns=[
            ColumnSpec("sku", str, required=True, auto=False),
            ColumnSpec("name", str, required=True),
            ColumnSpec("category", str, required=True),
            ColumnSpec("active", bool, required=True),
            ColumnSpec("selling_price", float, min_value=0.0000001),
            ColumnSpec("lifecycle", str, enum=("NEW", "GROWTH", "MATURE", "DECLINING", "EOL")),
            ColumnSpec("unit_volume_m3", float, min_value=0.0000001),
        ],
        dependents=(("sales_daily", "sku"), ("inventory_snapshots", "sku"),
                    ("vendor_offers", "sku"), ("policy_rules", "sku"), ("stock_receipts", "sku")),
    ),
    "warehouses": TableSpec(
        label="Warehouses",
        primary_key="warehouse_id",
        columns=[
            ColumnSpec("warehouse_id", str, required=True),
            ColumnSpec("name", str, required=True),
            ColumnSpec("storage_cost_per_m3_month", float, required=True, min_value=0),
        ],
        dependents=(("sales_daily", "warehouse_id"), ("inventory_snapshots", "warehouse_id"),
                    ("monthly_budgets", "warehouse_id"), ("policy_rules", "warehouse_id")),
    ),
    "inventory_snapshots": TableSpec(
        label="Stock snapshots",
        primary_key="snapshot_id",
        columns=[
            ColumnSpec("snapshot_id", str, auto=True),
            ColumnSpec("sku", str, required=True, fk=("products", "sku")),
            ColumnSpec("warehouse_id", str, required=True, fk=("warehouses", "warehouse_id")),
            ColumnSpec("on_hand", int, required=True, min_value=0),
            ColumnSpec("reserved", int, required=True, min_value=0),
            ColumnSpec("confirmed_inbound", int, required=True, min_value=0),
        ],
    ),
    "sales_daily": TableSpec(
        label="Daily sales",
        primary_key="sale_id",
        unique=("sale_date", "sku", "warehouse_id"),
        columns=[
            ColumnSpec("sale_id", str, auto=True),
            ColumnSpec("sale_date", date, required=True, not_future=True, label="Day"),
            ColumnSpec("sku", str, required=True, fk=("products", "sku")),
            ColumnSpec("warehouse_id", str, required=True, fk=("warehouses", "warehouse_id")),
            ColumnSpec("units_sold", int, required=True, min_value=0),
        ],
    ),
    "vendors": TableSpec(
        label="Vendors",
        primary_key="vendor_id",
        columns=[
            ColumnSpec("vendor_id", str, required=True),
            ColumnSpec("name", str, required=True),
            ColumnSpec("active", bool, required=True),
            ColumnSpec("on_time_rate", float, required=True, min_value=0, max_value=1),
            ColumnSpec("fill_rate", float, required=True, min_value=0, max_value=1),
            ColumnSpec("quality_score", float, required=True, min_value=0, max_value=1),
            ColumnSpec("billing_basis", str, enum=("ORDERED", "SHIPPED")),
            ColumnSpec("payment_terms_days", int, min_value=0),
            ColumnSpec("notes", str),
            ColumnSpec("contact_email", str),
        ],
        dependents=(("vendor_offers", "vendor_id"), ("stock_receipts", "vendor_id")),
    ),
    "vendor_offers": TableSpec(
        label="Vendor offers",
        primary_key="offer_id",
        columns=[
            ColumnSpec("offer_id", str, auto=True),
            ColumnSpec("vendor_id", str, required=True, fk=("vendors", "vendor_id")),
            ColumnSpec("sku", str, required=True, fk=("products", "sku")),
            ColumnSpec("unit_price", float, required=True, min_value=0.0000001),
            ColumnSpec("moq", int, required=True, min_value=1),
            ColumnSpec("lead_time_days", int, required=True, min_value=0),
            ColumnSpec("valid_until", str, required=True, label="Valid until"),
            ColumnSpec("freight_flat", float, min_value=0),
            ColumnSpec("freight_per_unit", float, min_value=0),
        ],
    ),
    "monthly_budgets": TableSpec(
        label="Monthly budgets",
        primary_key="budget_id",
        unique=("warehouse_id", "month"),
        columns=[
            ColumnSpec("budget_id", str, auto=True),
            ColumnSpec("warehouse_id", str, required=True, fk=("warehouses", "warehouse_id")),
            ColumnSpec("month", str, required=True, label="Month (YYYY-MM)"),
            ColumnSpec("budget_amount", float, required=True, min_value=0),
            ColumnSpec("spent_amount", float, min_value=0),
            ColumnSpec("committed_amount", float, min_value=0),
        ],
    ),
    "stock_receipts": TableSpec(
        label="Stock receipts",
        primary_key="receipt_id",
        columns=[
            ColumnSpec("receipt_id", str, auto=True),
            ColumnSpec("request_id", str),
            ColumnSpec("sku", str, required=True, fk=("products", "sku")),
            ColumnSpec("warehouse_id", str, required=True, fk=("warehouses", "warehouse_id")),
            ColumnSpec("vendor_id", str, required=True, fk=("vendors", "vendor_id")),
            ColumnSpec("quantity_ordered", int, required=True, min_value=0),
            ColumnSpec("quantity_received", int, required=True, min_value=0),
            ColumnSpec("ordered_at", str, required=True),
            ColumnSpec("promised_at", str, required=True),
            ColumnSpec("received_at", str, required=True),
            ColumnSpec("lead_time_days_actual", float, required=True, min_value=0),
        ],
    ),
    "policy_rules": TableSpec(
        label="Policy floors",
        primary_key="rule_id",
        columns=[
            ColumnSpec("rule_id", str, auto=True),
            ColumnSpec("sku", str, required=True, fk=("products", "sku")),
            ColumnSpec("warehouse_id", str, required=True, fk=("warehouses", "warehouse_id")),
            ColumnSpec("min_units", int, min_value=0),
            ColumnSpec("min_cover_days", float, min_value=0),
            ColumnSpec("reason", str, required=True),
            ColumnSpec("source", str, required=True),
            ColumnSpec("set_by", str, required=True, label="Set by"),
            ColumnSpec("effective_from", date, required=True),
            ColumnSpec("effective_to", date),
            ColumnSpec("active", bool, required=True),
        ],
    ),
    "carrying_cost_inputs": TableSpec(
        label="Carrying cost inputs",
        primary_key="input_id",
        unique=("effective_from",),
        columns=[
            ColumnSpec("input_id", str, auto=True),
            ColumnSpec("cost_of_capital_annual_rate", float, required=True, min_value=0),
            ColumnSpec("insurance_annual_rate", float, required=True, min_value=0),
            ColumnSpec("shrinkage_annual_rate", float, required=True, min_value=0),
            ColumnSpec("effective_from", date, required=True),
            ColumnSpec("set_by", str, required=True, label="Set by"),
            ColumnSpec("note", str),
        ],
    ),
}

INPUT_TABLES = tuple(TABLE_SPECS.keys())
