"""
Vendor-facing outbound PO email (Gap 8 / Upgrade 3, narrowed).

Deliberately its own file, separate from notifications/email.py (which only
ever emails the internal approver at config.email_to): this is the one
place in the system that sends a real commercial message to a third party,
so the trust boundary is explicit in the file structure, not just a
comment.

Content guardrail: every field in the message below comes from `proposal`
/ `purchase_result`, plus a read-only product-name/warehouse-name lookup --
all deterministic, code-computed or code-fetched values. Never a byte of
agent-generated free text (rationale, policy concerns, vendor notes)
reaches this template, so there is no prompt-injection surface even if
something upstream were compromised.

Authorization: only reachable from graph/nodes.execute_purchase, i.e. only
after the same human-approved + revalidated gate that already protects
create_purchase_request. There is no other path in.

DEPLOYMENT PREREQUISITE, NOT CODE: going live requires SPF/DKIM/DMARC
alignment on the sending domain (start DMARC at p=none, tighten to
p=reject only once monitoring shows clean alignment). That is an infra/DNS
task for whoever owns the sending domain -- out of scope for this
codebase. Until that review happens, config.vendor_email_enabled stays
False by default (submission/config.py), so this module sends nothing.
"""

from __future__ import annotations

import html
import re
import smtplib
from dataclasses import dataclass
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from domain.tool_models import PurchaseRequestResult, ReplenishmentProposal
from tools.execution import get_vendor_send_status, mark_vendor_send_status
from tools.inventory import get_product
from tools.vendors import get_vendor_contact_email
from tools.warehouses import get_warehouse

from submission.config import config


@dataclass(frozen=True)
class PurchaseOrderEmailPreview:
    """The exact deterministic message used for preview and eventual send."""

    recipient: str | None
    subject: str
    html_fragment: str
    html_document: str
    plain_text: str
    product_name: str
    warehouse_label: str


def _esc(value) -> str:
    return html.escape(str(value))


def _money(value) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "-"


def _date(value) -> str:
    try:
        return value.strftime("%d %b %Y")
    except AttributeError:
        return "-" if value is None else str(value)


_TAG_BREAK = re.compile(r"</(p|tr|h[1-6]|div|table)>", re.IGNORECASE)
_BR = re.compile(r"<br\s*/?>", re.IGNORECASE)
_TAG = re.compile(r"<[^>]+>")
_BLANK_RUN = re.compile(r"\n{3,}")


def _html_to_text(fragment: str) -> str:
    text = _BR.sub("\n", fragment)
    text = _TAG_BREAK.sub("\n", text)
    text = _TAG.sub("", text)
    text = html.unescape(text)
    text = re.sub(r"[ \t]+", " ", text)
    text = _BLANK_RUN.sub("\n\n", text)
    return text.strip()


def _wrap_html(inner: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Purchase Order</title>
</head>
<body style="margin:0;padding:0;background:#f4f5f7;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:24px 12px">
<tr><td align="center">
<table role="presentation" width="100%" style="max-width:600px;background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e7eb">
<tr><td style="background:#111827;padding:16px 24px">
<span style="color:#ffffff;font-size:14px;font-weight:600;letter-spacing:0.3px">{_esc(config.company_name)}</span>
</td></tr>
<tr><td style="padding:24px 24px 8px 24px;font-size:14px;line-height:1.6">
{inner}
</td></tr>
<tr><td style="padding:16px 24px;background:#f9fafb;border-top:1px solid #e5e7eb">
<p style="margin:0;color:#9ca3af;font-size:11px">This purchase order was generated by {_esc(config.company_name)}'s automated replenishment system. Reply to this email with any questions.</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def _send_vendor_email(to_address: str, subject: str, html_fragment: str) -> bool:
    if not (config.gmail_address and config.gmail_app_password):
        raise RuntimeError("VENDOR_EMAIL_ENABLED=true but GMAIL_ADDRESS/GMAIL_APP_PASSWORD not set")
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.gmail_address
    msg["To"] = to_address
    msg.attach(MIMEText(_html_to_text(html_fragment), "plain", "utf-8"))
    msg.attach(MIMEText(_wrap_html(html_fragment), "html", "utf-8"))
    with smtplib.SMTP(config.smtp_host, config.smtp_port) as server:
        server.starttls()
        server.login(config.gmail_address, config.gmail_app_password)
        server.sendmail(config.gmail_address, [to_address], msg.as_string())
    return True


def build_purchase_order_email_preview(
    proposal: ReplenishmentProposal, purchase_result: PurchaseRequestResult,
) -> PurchaseOrderEmailPreview:
    """Build the vendor message without sending it.

    This is deliberately the only template builder.  The Gate-2 screen uses
    its output before approval and ``send_purchase_order`` uses the same
    output afterward, so a human sees the precise message that will leave the
    system rather than an approximate UI summary.
    """
    # Read-only lookups purely to make the PO legible to a human at the
    # vendor -- a bare SKU code and a warehouse_id mean nothing to them.
    # Both are deterministic DB reads, not agent output, so the content
    # guardrail above still holds: nothing free-text or agent-generated
    # reaches this template.
    product = get_product(proposal.sku)
    product_name = product.name if product and product.error is None else proposal.sku
    warehouse = get_warehouse(proposal.warehouse_id)
    warehouse_label = f"{warehouse.name} ({proposal.warehouse_id})" if warehouse else proposal.warehouse_id

    body = f"""
    <p>Dear {_esc(proposal.recommended_vendor_name)} team,</p>
    <p>Please find below a new purchase order. Kindly confirm receipt and expected ship date at your earliest convenience.</p>
    <table role="presentation" width="100%" style="border-collapse:collapse;margin:16px 0">
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">PO reference</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0"><b>{_esc(purchase_result.request_id)}</b></td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">Item</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0">{_esc(product_name)} (SKU {_esc(proposal.sku)})</td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">Quantity</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0">{_esc(proposal.quantity)} units</td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">Unit price</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0">{_esc(_money(proposal.unit_price))}</td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">Total order value</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0"><b>{_esc(_money(proposal.total_cost))}</b></td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap;border-bottom:1px solid #f0f0f0">Deliver to</td>
          <td style="padding:6px 0;border-bottom:1px solid #f0f0f0">{_esc(warehouse_label)}</td></tr>
      <tr><td style="padding:6px 16px 6px 0;color:#666;white-space:nowrap">Requested delivery date</td>
          <td style="padding:6px 0"><b>{_esc(_date(proposal.expected_arrival))}</b></td></tr>
    </table>
    <p>Please reply to confirm this order and let us know if the requested delivery date is achievable.</p>
    <p>Thank you,<br>{_esc(config.company_name)}</p>
    """
    subject = f"Purchase Order {purchase_result.request_id} — {product_name} x{proposal.quantity}"
    return PurchaseOrderEmailPreview(
        recipient=get_vendor_contact_email(proposal.recommended_vendor_id),
        subject=subject,
        html_fragment=body,
        html_document=_wrap_html(body),
        plain_text=_html_to_text(body),
        product_name=product_name,
        warehouse_label=warehouse_label,
    )


def send_purchase_order(proposal: ReplenishmentProposal, purchase_result: PurchaseRequestResult) -> bool:
    """Send the same PO message previously shown at Gate 2.

    Returns True only if a send was attempted and succeeded; False if the
    gate is off, no recipient is configured, or the request was already sent.
    """
    if not config.vendor_email_enabled:
        return False

    sent_at, status = get_vendor_send_status(purchase_result.request_id)
    if sent_at is not None or status is not None:
        return False  # already attempted -- never double-send

    preview = build_purchase_order_email_preview(proposal, purchase_result)
    if not preview.recipient:
        return False

    ok = _send_vendor_email(preview.recipient, preview.subject, preview.html_fragment)
    mark_vendor_send_status(purchase_result.request_id, "SENT" if ok else "FAILED")
    return ok
